utils::globalVariables(c("where", "operatingunit",
                         "countryname", ".", "sheet",
                         "names_original", "value", "country",
                         "year", "iso", "indicator", "sex",
                         "indic_type", "headrs", "standardizeddisaggregate",
                         "fiscal_year", "ageasentered", "targets", "TX_CURR_SUBNAT",
                         "PLHIV", "ind", "type", "lower", "upper", "df_impatt",
                         "share_on_ART", "df_unaids", "label", "desc", "across",
                         "age", "deaths", "infections", "declining_deaths",
                         "infections_below_deaths", "old_rose", "denim", "fill_color",
                         "value_mod", "grey80k", "lab_pt", "val_lab"))
