utils::globalVariables(c("where", "operatingunit",
                         "countryname", ".", "sheet",
                         "names_original", "value", "country",
                         "year", "iso", "indicator", "sex",
                         "indic_type", "headrs", "standardizeddisaggregate",
                         "fiscal_year", "ageasentered", "targets", "TX_CURR_SUBNAT",
                         "PLHIV", "ind", "type", "lower", "upper", "df_impatt",
                         "share_on_ART", "df_unaids", "label", "desc", "across",
                         "age", "deaths", "infections", "declining_deaths",
                         "infections_below_deaths", "fill_color",
                         "value_mod", "lab_pt", "val_lab", "new_hiv_label",
                         "max_plot_pt", "aids_label", "min_plot_pt", "countryname_iso",
                         "high", "region", "low", "est", "country_iso", "estimate",
                         "upper_bound", "pepfar"))
